### ISSUE TITLE
FileConverter无法正常使用

### ISSUE THREAD

**Issue by leafmoes** [ivaquero/scoopet#105]
FileConverter的使用需要右键菜单，然后并没有

**Comment by leafmoes** [comment]
Can't retrieve the list of compatible input extensions (code0x09)
![image](https://github.com/ivaquero/scoopet/assets/44945631/e21b069d-b909-4b9f-9c25-072bf4bec1bd)

**Comment by ivaquero** [comment]
我这两天不在家，我回家后尽快看看。

**Comment by CronusLM** [comment]
官方的Nonportable库有这个软件建议，本库移除file-converter
https://github.com/ScoopInstaller/Nonportable/blob/master/bucket/file-converter-np.json

**Comment by CronusLM** [comment]
![2023-08-18_151122](https://github.com/ivaquero/scoopet/assets/72464074/c623b39d-aead-4e0d-a83e-ae40334ecf07)
经测试官方Nonportable库的file-converter可用

> Can't retrieve the list of compatible input extensions (code0x09) ![image](https://user-images.githubusercontent.com/44945631/261387732-e21b069d-b909-4b9f-9c25-072bf4bec1bd.png)

**Comment by ivaquero** [comment]
> 官方的Nonportable库有这个软件，建议本库移除file-converter
> 
> https://github.com/ScoopInstaller/Nonportable/blob/master/bucket/file-converter-np.json

我到家了就移除。

**Comment by leafmoes** [comment]
> ![2023-08-18_151122](https://user-images.githubusercontent.com/72464074/261528820-c623b39d-aead-4e0d-a83e-ae40334ecf07.png)经测试官方Nonportable库的file-converter可用
> 
> > 无法检索兼容的输入扩展列表 （code0x09）![图像](https://user-images.githubusercontent.com/44945631/261387732-e21b069d-b909-4b9f-9c25-072bf4bec1bd.png)

好的，非常感谢
