### ISSUE TITLE
Add Amazon Kindle

### ISSUE THREAD

**Issue by MingZhao2019** [ivaquero/scoopet#108]
Would you please consider adding the software Amazon Kindle to your bucket? FYI, it is a very useful software to read and can sync your reading process among different equipment.

App name: Amazon Kindle
Description: Amazon Kindle is a very useful software to read and can sync your reading process among different equipment.

Website: "https://www.amazon.com/b/ref=ruby_redirect?ie=UTF8&node=16571048011",
License: "Freeware",
Where to download: "https://www.amazon.com/b/ref=ruby_redirect?ie=UTF8&node=16571048011".

**Comment by ivaquero** [comment]
I will try at the weekend.

**Comment by ivaquero** [comment]
Done. Just type `scoop install amazon-kindle`.

**Comment by MingZhao2019** [comment]
Thank you for your support
