### ISSUE TITLE
eudic@2023-12-19: hash check failed

### ISSUE THREAD

**Issue by fhybj** [ivaquero/scoopet#115]
App:         scoopet/eudic
URL:         https://static.frdic.com/pkg/eudic_win.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    521a8e8401d8980a7fdb5b2a0898f5d00abba659c9a66a8f13ab877fc1fecd4e
Actual:      91968646ae43c19b199cb589253c68fdbfe8eb6be1f8e1b1ada78fec03da82b1

**Comment by fhybj** [comment]
Not work!
I tried running `scoop update; scoop cache rm eudic;`, but it still failed to check the hash.
I'm sure the network is working because I can update other apps.

**Comment by ivaquero** [comment]
I will fix later.

**Comment by ivaquero** [comment]
I tested and found the current hash is correct.
