### ISSUE TITLE
buzz@0.8.4: download failed

### ISSUE THREAD

**Issue by quanfun** [ivaquero/scoopet#119]
buzz源使用了ghproxy.com的文件代理，但是ghproxy.com已经GFW了，建议移除URI中的https://ghproxy.com/或修改为https://mirror.ghproxy.com/

Buzz source uses the file proxy of ghproxy.com, but ghproxy.com is already GFW. It is recommended to remove the file proxy in the URI https://ghproxy.com/  Or change to https://mirror.ghproxy.com/
![图片](https://github.com/ivaquero/scoopet/assets/162790307/cb78686a-30e5-4fae-b56c-41e5010e7704)

**Comment by ivaquero** [comment]
@quanfun 谢谢，已修复。
