### ISSUE TITLE
install utools failed: Cannot find path.....

### ISSUE THREAD

**Issue by xuchaoxin1375** [ivaquero/scoopet#133]
PS> sudo pwsh -c scoop install utools -g
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'utools' (5.1.0) [64bit] from 'scoopet' bucket
direct: https://open.u-tools.cn/download/uTools-5.1.0.exe#/dl.7z
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 958be7|OK  |    21MiB/s|C:/Users/cxxu/scoop/cache/utools#5.1.0#82cec3b.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of uTools-5.1.0.exe ... ok.
Extracting uTools-5.1.0.exe ... done.
Running installer script...done.
Linking C:\ProgramData\scoop\apps\utools\current => C:\ProgramData\scoop\apps\utools\5.1.0
Creating shortcut for uTools (uTools.exe)
Running post_install script...Remove-Item: Cannot find path 'C:\ProgramData\scoop\apps\utools\current\Uninstall uTools.exe' because it does not exist.
done.

**Comment by ivaquero** [comment]
更新了
