### ISSUE TITLE
diskgenius-cn 下载失败

### ISSUE THREAD

**Issue by isbest** [ivaquero/scoopet#137]
scoop install diskgenius-cn
Installing 'diskgenius-cn' (5.5.0.1488) [64bit] from 'scoopet' bucket
direct (Not in CN): https://download.geniusite.com/DG5501488_x64.zip
The SSL connection could not be established, see inner exception.
URL https://download.geniusite.com/DG5501488_x64.zip is not valid

**Comment by ivaquero** [comment]
中文版目前改成网盘下载了，需要再找找有没有其他链接
