### ISSUE TITLE
 N_m3u8DL-RE v0.3.0 更新命名格式再次改变

### ISSUE THREAD

**Issue by socratesng** [ivaquero/scoopet#140]
如题，版本号加入到了文件名中，beta首字母改为小写了，如x64版变成：
https://github.com/nilaoda/N_m3u8DL-RE/releases/download/v0.3.0-beta/N_m3u8DL-RE_v0.3.0-beta_win-x64_20241201.zip

**Comment by ivaquero** [comment]
已更新
