### ISSUE TITLE
the utools 6.0.0 hash check failed!

### ISSUE THREAD

**Issue by HanXiaoTeng** [ivaquero/scoopet#142]
utools: 5.2.1 -> 6.0.0
Updating 1 outdated apps:
Updating 'utools' (5.2.1 -> 6.0.0)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 93f77e|OK  |   1.2MiB/s|D:/Software/Scoop/cache/utools#6.0.0#40b87fa.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of uTools-6.0.0.exe ... ERROR Hash check failed!
App:         scoopet/utools
URL:         https://open.u-tools.cn/download/uTools-6.0.0.exe#/uTools.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    846179ab8332689217e4740ee30b7e92cf44837737a7a28405005279881de52a
Actual:      d9636e8038e6b1269c0a643c62cc5bd41d44c26655b476b449e14afcbe1c5978

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ivaquero/scoopet/issues/new?title=utools%406.0.0%3a+hash+check+failed

**Comment by ivaquero** [comment]
I updated it, please try again

**Comment by HanXiaoTeng** [comment]
> I updated it, please try again

It is ok,thanks.
