### ISSUE TITLE
vbox安装提示WARN  Bucket 'scoop-apps' not installed. Add it with 'scoop bucket add scoop-apps' or 'scoop bucket add scoop-apps <repo

### ISSUE THREAD

**Issue by zerols** [ivaquero/scoopet#23]
![image](https://user-images.githubusercontent.com/35661759/136213713-021e38fa-e354-4c0b-a93f-9e67969e3ce1.png)
![image](https://user-images.githubusercontent.com/35661759/136213927-9c34fc36-00bd-493b-a01e-6ae26be23c83.png)
这个报错跟这两个仓库名有关系嘛

**Comment by ivaquero** [comment]
刚看到，不好意思，这个是因为上游仓库有变动，我把脚本修改了一下，现在应该可以了
