### ISSUE TITLE
请求加入Edgeless

### ISSUE THREAD

**Issue by IsaacWangTT** [ivaquero/scoopet#26]
Edgeless是一个十分干净的PE系统工具，官网为https://home.edgeless.top/
下载下来的包就是便携版，望添加

**Comment by ivaquero** [comment]
我没大看明白，便携版的链接在哪？我能找到的就是 [edgeless](https://zfile.edgeless.top/2/main/Socket) 这个链接下的一个，iso 文件，但是怎么用 scoop 处理 iso 我也不会。

**Comment by IsaacWangTT** [comment]
> 我没大看明白，便携版的链接在哪？我能找到的就是 [edgeless](https://zfile.edgeless.top/2/main/Socket) 这个链接下的一个，iso 文件，但是怎么用 scoop 处理 iso 我也不会。

你改了UA吧😂，直链在这https://pineapple.edgeless.top/disk/Socket/Hub/Edgeless%20Hub_Beta_2.25.7z

**Comment by ivaquero** [comment]
我很想帮忙，不过我现在改用苹果了，没法做本地测试了，你试着写了个脚本，不确定能不能成功，你试试吧。

如果有问题，你可以选择

1. 提 issue
2. 写个 PR
3. 自己建个仓库

**Comment by IsaacWangTT** [comment]
> 我很想帮忙，不过我现在改用苹果了（这也是我开始没能获取正确下载链接的原因），没法做本地测试了，你试着写了个脚本，不确定能不能成功，你试试吧。
> 
> 如果有问题，你可以选择
> 
>     1. 继续在 issue 沟通
> 
>     2. 写个 PR
> 
>     3. 自己建个仓库

你好，有个小错误，应该是脚本的路径问题，该包解压后多了个Edgeless Hub父目录，Edgeless Hub/启动程序
