### ISSUE TITLE
Edgeless的脚本有错误

### ISSUE THREAD

**Issue by IsaacWangTT** [ivaquero/scoopet#28]
一个小错误，路径问题，该包解压后多了个Edgeless Hub父目录，Edgeless Hub/启动程序

**Comment by ivaquero** [comment]
这个脚本我没法进行测试，我目前手边没有 Win 的电脑，你看你能不能帮忙给改一下。

**Comment by IsaacWangTT** [comment]
> 这个脚本我没法进行测试，我目前手边没有 Win 的电脑，你看你能不能帮忙给改一下。

乐意帮忙，请问我该怎么操作

**Comment by IsaacWangTT** [comment]
> 这个脚本我没法进行测试，我目前手边没有 Win 的电脑，你看你能不能帮忙给改一下。

乐意帮忙，已提交请求

**Comment by ivaquero** [comment]
非常感谢，如果你想成为仓库管理员，告诉我。

**Comment by IsaacWangTT** [comment]
> 非常感谢，如果你想成为仓库管理员，告诉我。

非常乐意，但我目前是在校生，可能帮不了多少忙，请见谅

**Comment by ivaquero** [comment]
很感谢了。发了邀请了。
