### ISSUE TITLE
Wise Care 365 请求更新

### ISSUE THREAD

**Issue by IsaacWangTT** [ivaquero/scoopet#32]

**Comment by ivaquero** [comment]
我现在手头没有 win，你有空的话，帮忙搞一搞吧

**Comment by IsaacWangTT** [comment]
> 我现在手头没有 win，你有空的话，帮忙搞一搞吧

我之前弄过，但是被你的github action改回去了😂

**Comment by ivaquero** [comment]
> > 我现在手头没有 win，你有空的话，帮忙搞一搞吧
> 
> 我之前弄过，但是被你的github action改回去了😂

**Comment by ivaquero** [comment]
> > 我现在手头没有 win，你有空的话，帮忙搞一搞吧
> 
> 我之前弄过，但是被你的github action改回去了😂

我看一下

**Comment by ivaquero** [comment]
我看到了，是 hash 不对

**Comment by IsaacWangTT** [comment]
> 我看到了，是 hash 不对

哦哦，第一次搞这些，学校还没教，弄得有点生疏😂

**Comment by ivaquero** [comment]
我知道了，这个是 checkver 造成的，因为目前官网的信息没有更新，所以，无论怎么改，github action 都会改回去。这样的问题有2个方法

1. 删掉 checkver，这样就不能自动更新了
2. 找到其他记录 version 信息的地方

**Comment by IsaacWangTT** [comment]
> 我知道了，这个是 checkver 造成的，因为目前官网的信息没有更新，所以，无论怎么改，github action 都会改回去。这样的问题有2个方法
> 
>     1. 删掉 checkver，这样就不能自动更新了
> 
>     2. 找到其他记录 version 信息的地方
> 
> 
> 目前的 checkver 追踪的地址，[checkver](https://www.wisecleaner.com/software_update/getinfo.php?p_id=23)

那我就先手动更新吧，十分感谢

**Comment by ivaquero** [comment]
> > 我看到了，是 hash 不对
> 
> 哦哦，第一次搞这些，学校还没教，弄得有点生疏😂

如果方便的话，我加你的推，后面有什么问题，咱们上面说

**Comment by IsaacWangTT** [comment]
> > > 我看到了，是 hash 不对
> > 
> > 
> > 哦哦，第一次搞这些，学校还没教，弄得有点生疏😂
> 
> 如果方便的话，我加你的推，后面有什么问题，咱们上面说

可以的
