### ISSUE TITLE
[Request]请求加入Sysinternals

### ISSUE THREAD

**Issue by CronusLM** [ivaquero/scoopet#41]
Sysinternals是一个微软收购的一个系统管理工具包，有很多有用的工具，全是绿色软件，有微软商店的安装方式，但是微软商店我用起来感觉很难受，而且微软没有一个专门的文件夹放快捷方式，导致开始菜单很乱。
主页：https://docs.microsoft.com/zh-cn/sysinternals/
下载：https://docs.microsoft.com/zh-cn/sysinternals/downloads/
里面的软件很多，而且分64位和32位软件都在一个压缩包里，这样软件主页的自动更新脚本我不会写

**Comment by ivaquero** [comment]
麻烦稍微等一下，目前在封控，手边没有 win 电脑

**Comment by ivaquero** [comment]
看到 extras 库，是有这个软件的，所以这个 issue 关闭了。

**Comment by CronusLM** [comment]
我之前搜我导出的软件列表没搜到，看来打出前几个字母搜就行了
