### ISSUE TITLE
utools还是有问题

### ISSUE THREAD

**Issue by CronusLM** [ivaquero/scoopet#45]
Installing 'utools' (2.6.3) [64bit]
uTools-2.6.3.exe (62.4 MB) [===================================================================================================================================================================================================] 100%
Checking hash of uTools-2.6.3.exe ... ok.
Extracting dl.7z ... done.
Running installer script...
Linking ~\scoop\apps\utools\current => ~\scoop\apps\utools\2.6.3
Creating shortcut for uTools (uTools.exe)
Running post-install script...
Remove-Item : 找不到路径“C:\Users\Kronus\scoop\apps\utools\current\Uninstall uTools.exe”，因为该路径不存在。
所在位置 行:1 字符: 1
+ Remove-Item "$dir\`$PLUGINSDIR", "$dir\Uninstall uTools.exe" -Force - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Kronus...tall uTools.exe:String) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

'utools' (2.6.3) was installed successfully!

最后能安装成功，就是post-install会报错

**Comment by ivaquero** [comment]
我手边暂时没有win，目前处理不了
