### ISSUE TITLE
tencent-meeting 更新了

### ISSUE THREAD

**Issue by Avenzhao** [ivaquero/scoopet#57]
下载URL
https://updatecdn.meeting.qq.com/cos/22bff9645b667336c2e37ab1993e77d3/TencentMeeting_0300000000_3.9.7.407.publish.exe

**Comment by JaimeZeng** [comment]
这软件更新地址一直变，懒得 pr 了，直接用这个 [文件](https://github.com/Ryanjiena/Tian/blob/main/bucket/tencent-meeting.json) 吧

**Comment by ivaquero** [comment]
> 这软件更新地址一直变，懒得 pr 了，直接用这个 [文件](https://github.com/Ryanjiena/Tian/blob/main/bucket/tencent-meeting.json) 吧

更新了
