### ISSUE TITLE
钉钉无法登录的解决办法

### ISSUE THREAD

**Issue by LXYan2333** [ivaquero/scoopet#61]
win10系统，scoop安装钉钉后无法扫码登陆，提示“为了你的帐号安全，请更新到最新版本后登录”。

查看钉钉官网，发现本bucket中的钉钉为6.0.8版，属于最后一个可以在XP/Vista使用的版本（[链接](https://terms.alicdn.com/legal-agreement/terms/suit_bu1_dingtalk/suit_bu1_dingtalk202204021702_82345.html?spm=a3140.8196062.0.0.6f4c1b4bq4vyoE)）
国内那么多人用XP，钉钉不可能说直接放弃它们。于是合理猜想，使用兼容模式运行可以解除限制。

操作步骤：

1. 完全关闭钉钉。记得右下角状态栏的钉钉也右键退出。（实在不行用任务管理器杀掉）
2. 于是将钉钉改为兼容模式运行，兼容性选择XP（Vista估计也行，没试过）
3. 直接扫码登录，成功
4. 关闭兼容模式，此后可以直接登录，不用再授予管理员权限。

**Comment by ivaquero** [comment]
更新了钉钉的脚本

**Comment by ivaquero** [comment]
感谢反馈。
