### ISSUE TITLE
为什么小狼毫能安装不能卸载呢？

### ISSUE THREAD

**Issue by usnake** [ivaquero/scoopet#62]
PS C:\Windows\system32> scoop uninstall weasel
Uninstalling 'weasel' (0.14.3.0).
Running uninstaller... error.
ERROR 使用“0”个参数调用“Start”时发生异常:“拒绝访问。”
Uninstallation aborted.

用管理员ps和非管理员都试过了不行呢

**Comment by ivaquero** [comment]
这个我也确定，需要一些时间探究

**Comment by ivaquero** [comment]
我这边可以以管理员身份卸载，但是得两遍，我不大清楚原因。

**Comment by usnake** [comment]
我后来在安装文件夹直接运行uninstall.exe卸载了

**Comment by SiyuChen** [comment]
可以使用
    "uninstaller": {
        "script": "Invoke-ExternalCommand \"$dir\\uninstall.exe\"-ArgumentList '/S' -RunAs | Out-Null"
    }
卸载

**Comment by ivaquero** [comment]
> 可以使用 "uninstaller": { "script": "Invoke-ExternalCommand "$dir\uninstall.exe"-ArgumentList '/S' -RunAs | Out-Null" } 卸载

感谢，已更新
