### ISSUE TITLE
wpsoffice-cn is not the latest version

### ISSUE THREAD

**Issue by git136975643** [ivaquero/scoopet#63]
Windows version of wps office

**Comment by ivaquero** [comment]
Yes, wpsoffice-cn has changed its version syntax. We need some time to fix it.

**Comment by ivaquero** [comment]
We need some time to investigate how to install the newest official release.

**Comment by git136975643** [comment]
There is also Microsoft Office, do you have any office three-piece suites like office365, such as office-tool-plus

**Comment by git136975643** [comment]
中文版的😊

**Comment by ivaquero** [comment]
目前没有，商业软件安装经常需要各种权限，你可以看看用 winget 能不能安装

**Comment by ivaquero** [comment]
我更新了一下，wps中文版，一会儿看看能不能用

**Comment by git136975643** [comment]
Podman Desktop 这个有中文版嘛😁

**Comment by ivaquero** [comment]
> Podman Desktop 这个有中文版嘛😁

没有，我没用过，你可以提交一个PR，我合并

**Comment by ivaquero** [comment]
我看你英语不错啊，何苦要用中文的呢

**Comment by git136975643** [comment]
我没写过scoop的清单json。不会
怕podman以后功能界面增加多，中文看得爽一点。从docker过渡到podman。我的编辑器VSCode都用的中文界面（中文插件）。

**Comment by ivaquero** [comment]
这东西不难，你找个podman的json，替换一下链接和文件名，试一下

**Comment by git136975643** [comment]
你markdown里的Step 2 没有写全局路径，你那个是 scoop install <app> 的；没有scoop install -g <app> 的。

**Comment by ivaquero** [comment]
> 你markdown里的Step 2 没有写全局路径，你那个是 scoop install <app> 的；没有scoop install -g <app> 的。

是的。我平时很少全局安装，因为全局的话意味着需要管理员权限，这个和 scoop 的理念不大相衬。

**Comment by git136975643** [comment]
我目前喜欢powershell 7.2.6版本（Windows默认是5版本） + scoop（设置全改到D盘指定的文件夹了） + wsl2

**Comment by ivaquero** [comment]
我习惯于把程序全部放在C盘，个人文件全部放在D盘。

**Comment by ivaquero** [comment]
WPS版本问题目前解决了，我先把issue关了。

**Comment by ivaquero** [comment]
> Podman Desktop 这个有中文版嘛😁

@git136975643 podman desktop 中文版的链接，你能不能提供一下

**Comment by git136975643** [comment]
> > Podman Desktop 这个有中文版嘛😁
> 
> @git136975643podman desktop 中文版的链接，你能提供一下，我没找到

本来就是外国人写的，没有中文版。。。 我以为你们能搞这些，还有idea、goland、python、Photoshop等等的破解版🙏

**Comment by ivaquero** [comment]
> > > Podman Desktop 这个有中文版嘛😁
> > 
> > 
> > @git136975643podman desktop 中文版的链接，你能提供一下，我没找到
> 
> 本来就是外国人写的，没有中文版。。。 我以为你们能搞这些，还有navicat-premium、idea、goland、python、Photoshop等等的破解版🙏

那搞不来。
