### ISSUE TITLE
Tencet Meeting doesn't launch. 

### ISSUE THREAD

**Issue by peacemo** [ivaquero/scoopet#70]
```
OS: Windows 11 专业版 x86_64
Host: HP OMEN Laptop 15-en0xxx
Kernel: 10.0.22621
Uptime: 19 hours, 7 mins
Shell: bash 5.1.16
Resolution: 1920x1080, 2560x1440
DE: Aero
WM: Explorer
WM Theme: Custom
Terminal: Windows Terminal
CPU: AMD Ryzen 7 4800H with Radeon Graphics (16) @ 2.900GHz
GPU: Caption
GPU: AMD Radeon(TM) Graphics
GPU: NVIDIA GeForce GTX 1650 Ti
GPU
Memory: 7609MiB / 15732MiB
```

Above is my machine info, the TENCENT MEETING doesn't launch after installing. I tried reboot my PC but it did nothing. The official install version can launch properly.

**Comment by ivaquero** [comment]
Thank you for reporting. I just roll back the version to 3.5.6.416.

**Comment by ivaquero** [comment]
If it works on your computer, this issue can be closed.

**Comment by peacemo** [comment]
> If it works on your computer, this issue can be closed.

It works
