### ISSUE TITLE
[Request]请求加入CAJViewer

### ISSUE THREAD

**Issue by Meng5in** [ivaquero/scoopet#8]
CAJViewer 7.3 UI好看了那么一点，这个对大学生真的是刚需……
麻烦了！！！

**Comment by integzz** [comment]
刚看到，我试一下

**Comment by integzz** [comment]
刚看到，这个软件打包结构对我来说有点复杂，我能力有限，暂时做不了。

**Comment by Meng5in** [comment]
谢谢回复！CAJ没PDF通用，所以我找了个能直接下载PDF的插件……
也算是曲线救国了😂

**Comment by integzz** [comment]
是的，尽量还是用PDF，文献引用的时候也方便。

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
