### ISSUE TITLE
scoop install vmware-workstation-pro error on windows10

### ISSUE THREAD

**Issue by anye88** [ivaquero/scoopet#86]
![image](https://user-images.githubusercontent.com/43066668/229340347-9c455a0f-ef0b-45fb-b796-0db4c8637432.png)

**Comment by ivaquero** [comment]
测试了一下，安装器无法传出参数，不确定什么地方出了问题

**Comment by wenxuanjun** [comment]
@anye88 Use PowerShell 7 and problem solved.

**Comment by zhkag** [comment]
经测试，路径中不应该含有 "-" 符号 改下包名应该就行了

**Comment by ivaquero** [comment]
更新了，没有问题了
