### ISSUE TITLE
n-m3u8dl-re 无法下载

### ISSUE THREAD

**Issue by hiiiha** [ivaquero/scoopet#95]
https://github.com/nilaoda/N_m3u8DL-RE/releases 已经更新到0.18了，(貌似还没自动更新？)

另：目前此 bucket 中的 0.16 版无法下载（resource not found）

**Comment by ivaquero** [comment]
我晚上看一下

**Comment by hiiiha** [comment]
不用看了，估计等会自动更新就好了
